// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v5.29.2
// source: plugin.proto

package proto

import (
	context "context"
	emptypb "github.com/knqyf263/go-plugin/types/known/emptypb"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// go:plugin type=host
type HostFunctions interface {
	// Log a message
	Logger(context.Context, *Message) (*emptypb.Empty, error)
}

// The plugin service definition.
// go:plugin type=plugin version=1
type Plugin interface {
	// Handle data
	Handle(context.Context, *Event) (*Event, error)
}
