// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin 0.8.0
// 	protoc               v5.28.0
// source: plugin.proto

package proto

import (
	context "context"
	emptypb "github.com/knqyf263/go-plugin/types/known/emptypb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line string `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
}

func (x *Message) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *Message) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

// The event.
type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts     int32   `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Serial string  `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Value  float32 `protobuf:"fixed32,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Event) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *Event) GetTs() int32 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Event) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *Event) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// go:plugin type=host
type HostFunctions interface {
	// Log a message
	Logger(context.Context, *Message) (*emptypb.Empty, error)
}

// The plugin service definition.
// go:plugin type=plugin version=1
type Plugin interface {
	// Handle data
	Handle(context.Context, *Event) (*Event, error)
}
